### ISSUE TITLE
fuck anti adblock link to google is not working

### ISSUE THREAD

**Issue by formatme** [mun3/F-ckAvgleAntiAdblock#10]
so i saw the new update at the top for a stream to google but when i click it, it takes me to the same url but with"/undefined" after it

**Comment by formatme** [comment]
not sure why it wasn't working but now it is. i turned of my adblocker and turned it back on so im not sure if that fixed it.

**Comment by mun3** [comment]
It could be a race condition. I've added some code to address that now.
