### ISSUE TITLE
m3u8流合并的问题

### ISSUE THREAD

**Issue by Fezreal** [mun3/F-ckAvgleAntiAdblock#11]
刚刚更新了一下，发现居然多了下载的功能， 真的太厉害了。 

https://avgle.com/video/131612
![image](https://user-images.githubusercontent.com/6703674/35607890-9063675a-0691-11e8-99ac-948a8c442eb9.png)
以这个视频为例， 它的总长度是4小时，被切分成了很多个流， 有什么办法能合并了再下载吗？

**Comment by mogu1121** [comment]
复制 "HERE" 的链接 用ffmpeg下载
`ffmpeg -i "m3u8url" -c copy v.mp4`
但是链接是有时间限制的 ffmpeg 一个一个下载ts很慢
建议用idm或者aria2c批量下载
里面的链接是这样的
`https://ip54177648.ahcdn.com/key=DA3Hd99wQ9+DzGN-PonpUw,s=,end=1517459912,limit=2/data=1517459912/state=c4cm/reftag=56109644/media=hlsA/ssd8/177/8/79373948.mp4/seg-1431-v1-a1.ts`
`aria2c -P -Z "https://ip54177648.ahcdn.com/key=DA3Hd99wQ9+DzGN-PonpUw,s=,end=1517459912,limit=2/data=1517459912/state=c4cm/reftag=56109644/media=hlsA/ssd8/177/8/79373948.mp4/seg-[1-1431]-v1-a1.ts"`
下载好了以后编辑m3u8
`https://ip54177648.ahcdn.com/key=DA3Hd99wQ9+DzGN-PonpUw,s=,end=1517459912,limit=2/data=1517459912/state=c4cm/reftag=56109644/media=hlsA/ssd8/177/8/79373948.mp4/seg-1431-v1-a1.ts`
改成这样的格式 井号也留着
`seg-1-v1-a1.ts
seg-...-v1-a1.ts
seg-1431-v1-a1.ts`
`ffmpeg -i m3u8 -c copy v.mp4`
这样就好了
