### ISSUE TITLE
stopped working again

### ISSUE THREAD

**Issue by Yodamt** [mun3/F-ckAvgleAntiAdblock#12]
i'm sure i 've got ublock origin and tampermonkey and version 0.11.14 installed
however 

> Please disable adblocker or whitelist avgle.com! No ads, Avgle cannot survive!

still appeared

**Comment by hoonkai** [comment]
Fixed.

**Comment by mun3** [comment]
It should be fixed now.

**Comment by chae-won-chae** [comment]
Doesnt work for me. The page reload after a while.

![log-ublock](https://user-images.githubusercontent.com/20675587/35650772-3c4a404e-0718-11e8-84a7-107dcc21404d.png)

**Comment by nellem** [comment]
blocked again... sigh

**Comment by mun3** [comment]
Are you on 0.11.16?

**Comment by nellem** [comment]
found why it wasn't working, it was due to the "Adguard Base Filters"
It seem like version 0.11.16 works perfectly fine :) thank you

**Comment by chae-won-chae** [comment]
working for me too. somehow theres two different version got installed and messed up/prevent the latest update. i have since deleted both and reinstall. Thank you.
