### ISSUE TITLE
0.11.24 failed

### ISSUE THREAD

**Issue by Fezreal** [mun3/F-ckAvgleAntiAdblock#13]
![image](https://user-images.githubusercontent.com/6703674/35676656-8ab1bfd6-0787-11e8-925d-d7af93e24593.png)

**Comment by mun3** [comment]
Yes, they've decided to ban everyone who blocks their ads. Quite a radical and dumb move. It seems to be a sacrifice they're willing to make.

**Comment by Fezreal** [comment]
@mun3 update the script, let's start the war,

---
操回去啊，干

**Comment by mogu1121** [comment]
@Fezreal 他们在这里看吗

**Comment by Fezreal** [comment]
@mogu1121 avgle的网站管理肯定在啊， 从easylist那边帖子的跟过来的。

**Comment by mogu1121** [comment]
@Fezreal 你是要收藏还是看， isafe广告没有以前多 可以用它下载 是mp4版本

**Comment by Fezreal** [comment]
@mogu1121  闲的时候看一下。。 下载一般查了番号再115

**Comment by mogu1121** [comment]
@Fezreal 看来是vip啊 50kb我受不了

**Comment by Fezreal** [comment]
@mogu1121 京东搜115会员，350块一年

**Comment by mun3** [comment]
@Fezreal It's almost depressing to see how desperate and pathetic they are actually. Let's not even talk about them breaking their site the laughable number of times just from patching against this script. The ads are so intrusive, so no sane Adblock user would ever whitelist them.

They are noobs running the site. They don't get how to make money from a porn site.

**Comment by Fezreal** [comment]
这个网站的广告太多了，如果不过滤，我这个中等配置的笔记本电脑直接给卡死了。 操

**Comment by mogu1121** [comment]
作者看不看得懂中文啊
我的想法是广告加载完后 移除干净
但是有个问题 就是
播放视频后还会执行检测 能搞定吗
`window.addEventListener('load', () => {`
`	for (let a=0; a<9999;a++)clearInterval(a);`
`	for (let a=0; a<9999;a++)clearTimeout(a);`
`	for (let a of document.querySelectorAll('center'))a.remove();`
`	for (let a of document.querySelectorAll('iframe'))a.remove();`
`	player_3x2_close.click();`
`});`

**Comment by Fezreal** [comment]
他应该是国人

**Comment by tess1199** [comment]
any body knows how decode the avgle-main-ah.js?
this js is the key, but it confused... if there is a tool or method decode it , everything is easy!!

**Comment by mun3** [comment]
@mogu1121 We can continue the discussion on the side if you want. I'm on IRC Freenode: /j #faaa.

**Comment by mun3** [comment]
@tess1199 We can continue the discussion on the side if you want. I'm on IRC Freenode. Join #faaa.

**Comment by mogu1121** [comment]
@mun3 我不是很懂js

**Comment by mun3** [comment]
@mogu1121 That's OK. We've all been there.

**Comment by mogu1121** [comment]
我进入了吗

**Comment by tess1199** [comment]
@mun3 I haven't use irc yet, i go to study it at first.

**Comment by Fezreal** [comment]
啊  请不要放弃 我亲爱的朋友呐

**Comment by mun3** [comment]
I've given the script a makeover already, but I'm not pushing the commit just yet.

**Comment by mun3** [comment]
Much of the effort and discussion has been moved to IRC. See above.

**Comment by Fezreal** [comment]
![image](https://user-images.githubusercontent.com/6703674/35765844-a550840e-0907-11e8-88b2-6a3a1a67c050.png)
![image](https://user-images.githubusercontent.com/6703674/35765846-aec0a1f4-0907-11e8-9e33-c5785cba5b04.png)

这个dave4925是你吗? @mun3

**Comment by mogu1121** [comment]
@Fezreal 只有 井faaa

**Comment by vi000246** [comment]
或許可以把avgle-main-ah.js 封掉，再用Tampermonkey載進來 一段一段註解，測看看哪段是擋adblock的語法
Maybe we can block avgle-main-ah.js,Then load it from Tampermonkey, test which part is anti-adblock code.

**Comment by mun3** [comment]
Fixed.
