### ISSUE TITLE
How to get m3u8 url

### ISSUE THREAD

**Issue by Graviiii** [mun3/F-ckAvgleAntiAdblock#14]
Hi guys,

Great job you have done so far. So I initially had a script that was able to download avgle videos from url, but ever since avgle changed the way they display the m3u8 url, I haven't been able to get access to it. They are now using videojs, and I don't know too much about it.

I saw before that one of the updates was able to display a link to the m3u8 url. Is there any way currently to get access to the m3u8 link (through script or manual inspecting through devtools)?

Thanks for any help you can provide :)

**Comment by Graviiii** [comment]
If there isn't, then no problem.
Thanks guys.

**Comment by mun3** [comment]
Fixed.
