### ISSUE TITLE
0.11.32 blocked

### ISSUE THREAD

**Issue by nellem** [mun3/F-ckAvgleAntiAdblock#19]
##### System information (version)

- F-ckAvgleAntiAdblock => 0.11.32
- Operating System / Platform => Mac High Sierra 10.13.3

##### Detailed description

 Using Chrome with 0.11.32 and it has been blocked again. Shows" Remove Tampermonkey/Violentmonkey userscript and come back 24 hours later, or masturbate on DMM R18 from now on!" message again.

##### uBlockOrigin's "My Filters"
avgle.com###player_3x2_container
@@||avgle.com/avideos.php
avgle.com#@#script:inject(abort-on-property-read.js, ExoDetector)

**Comment by mun3** [comment]
I'm unable to reproduce the error. Have you tried Safari or Firefox?
