### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by formatme** [mun3/F-ckAvgleAntiAdblock#5]
under the firefox section update the url, with https://raw.githubusercontent.com/mun3/F-ckAvgleAntiAdblock/master/fu_antiadblock.js

**Comment by formatme** [comment]
https://github.com/mun3/F-ckAvgleAntiAdblock/raw/master/fu_antiadblock.user.js 404s

**Comment by mun3** [comment]
Filename is changed for better usability. Please reinstall as per current Readme.

**Comment by mun3** [comment]
Someone had to. :)
