### ISSUE TITLE
0.11.10 Virus?

### ISSUE THREAD

**Issue by ghost** [mun3/F-ckAvgleAntiAdblock#7]
when i update to version 0.11.10

火绒提示
病毒名称：SVM:TrojanDownloader/JS.MalBehav.gen!D
病毒ID：6D99EEAA0D65948B

**Comment by Fezreal** [comment]
火绒的问题而已 ， 火绒的下载保护基本上没用， 啥网页都乱报毒。
而且现在的浏览器是入沙的，不管你JS干什么，都不会对实机产生影响。
