### ISSUE TITLE
0.11.10 failure now

### ISSUE THREAD

**Issue by Fezreal** [mun3/F-ckAvgleAntiAdblock#8]

**Comment by mun3** [comment]
Try adding `@@||avgle.com/avideos.php` to your filters.

**Comment by Fezreal** [comment]
![image](https://user-images.githubusercontent.com/6703674/35550683-8f5dd06e-05c6-11e8-9dbb-b5624c85ac48.png)

能把这个过滤掉吗，这个广告不会随着播放而自动关闭，每次都要手动点了。 挺麻烦的。

**Comment by mun3** [comment]
Which browser?
Show me your uBO log.

**Comment by Fezreal** [comment]
chrome
![image](https://user-images.githubusercontent.com/6703674/35550797-011205cc-05c7-11e8-83a9-a1314f9359a3.png)
![image](https://user-images.githubusercontent.com/6703674/35550824-1582a43a-05c7-11e8-97cf-ed001edf2764.png)

**Comment by mun3** [comment]
Add
`avgle.com###player_3x2_container`
`@@||avgle.com/avideos.php`
